#pragma once
#include <iostream>
#include <exception>
#include <string>
#include "Enumerations.h"
#include "Structs.h"
#include "DemoStructs.h"
#include "DemoExceptions.h"
#include "Color.h"
#include "Genre.h"
#include "SmartphoneManufacturer.h"
#include "StudyForm.h"
#include "WeekDay.h"
#include "YearTime.h"